// @ts-nocheck
import { createFileRoute, Link } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useState } from "react";
import { Bot, Plus, Trash2, MessageCircle, Radio, Save, Search, Shield, Activity } from "lucide-react";
import { toast } from "sonner";
import { AssistantShell } from "@/components/samsta/AssistantShell";
import { supabase } from "@/integrations/supabase/client";
import { useAuthUser } from "@/hooks/use-auth";
import { listFollowers, type PublicProfile } from "@/lib/api/social";
import { getMyAvailability } from "@/lib/twin.functions";

export const Route = createFileRoute("/assistants/digital-twin")({ component: TwinPage });

const ACCENT = "linear-gradient(135deg, oklch(0.35 0.04 20), oklch(0.5 0.1 30))";

type BusyWindow = { days?: number[]; from?: string; to?: string; label?: string };
type Twin = {
  user_id: string; persona_prompt: string; tone: string;
  is_enabled: boolean; auto_reply_dm: boolean;
  allow_public_ask: boolean; allow_twin_to_twin: boolean;
  availability_detection: boolean; manual_status: string; focus_mode: boolean;
  busy_schedule: BusyWindow[]; auto_reply_label: string;
};
type Routine = { id: string; title: string; schedule: string | null; instructions: string };
type Convo = { id: string; initiator_id: string; target_user_id: string; kind: string; title: string | null; updated_at: string };


function TwinPage() {
  const { user } = useAuthUser();
  const [twin, setTwin] = useState<Twin | null>(null);
  const [routines, setRoutines] = useState<Routine[]>([]);
  const [followers, setFollowers] = useState<PublicProfile[]>([]);
  const [convos, setConvos] = useState<Convo[]>([]);
  const [tab, setTab] = useState<"setup" | "routines" | "followers" | "chat" | "inbox">("setup");
  const [searchQ, setSearchQ] = useState("");
  const [searchResults, setSearchResults] = useState<PublicProfile[]>([]);
  const [saving, setSaving] = useState(false);
  const [newR, setNewR] = useState<{ title: string; schedule: string; instructions: string }>({ title: "", schedule: "", instructions: "" });
  const [status, setStatus] = useState<{ status: "available" | "busy"; reason: string } | null>(null);
  const fetchStatus = useServerFn(getMyAvailability);

  useEffect(() => {
    if (!user) return;
    fetchStatus().then(setStatus).catch(() => {});
    const i = window.setInterval(() => fetchStatus().then(setStatus).catch(() => {}), 30000);
    return () => window.clearInterval(i);
  }, [user?.id]);


  useEffect(() => {
    if (!user) return;
    (async () => {
      const { data: t } = await supabase.from("digital_twins").select("*").eq("user_id", user.id).maybeSingle();
      const base: Twin = {
        user_id: user.id, persona_prompt: "", tone: "friendly",
        is_enabled: false, auto_reply_dm: true, allow_public_ask: true, allow_twin_to_twin: true,
        availability_detection: true, manual_status: "auto", focus_mode: false,
        busy_schedule: [], auto_reply_label: "Generated by Sam",
      };
      setTwin(t ? { ...base, ...(t as any), busy_schedule: Array.isArray((t as any).busy_schedule) ? (t as any).busy_schedule : [] } : base);
      const { data: r } = await supabase.from("twin_routines").select("*").eq("user_id", user.id).order("created_at", { ascending: false });
      setRoutines(r ?? []);
      const f = await listFollowers(user.id).catch(() => []);
      setFollowers(f);
      const { data: c } = await supabase.from("twin_conversations").select("*")
        .or(`initiator_id.eq.${user.id},target_user_id.eq.${user.id}`).order("updated_at", { ascending: false }).limit(30);
      setConvos(c ?? []);
    })();
  }, [user?.id]);

  const save = async () => {
    if (!twin || !user) return;
    setSaving(true);
    const { error } = await supabase.from("digital_twins").upsert({ ...twin, user_id: user.id });
    setSaving(false);
    if (error) toast.error(error.message); else toast.success("Twin saved");
  };
  const addRoutine = async () => {
    if (!user || !newR.title.trim() || !newR.instructions.trim()) return;
    const { data, error } = await supabase.from("twin_routines").insert({ ...newR, user_id: user.id }).select("*").single();
    if (error) return toast.error(error.message);
    setRoutines([data as Routine, ...routines]); setNewR({ title: "", schedule: "", instructions: "" });
  };
  const delRoutine = async (id: string) => {
    await supabase.from("twin_routines").delete().eq("id", id);
    setRoutines(routines.filter((r) => r.id !== id));
  };
  const runSearch = async (q: string) => {
    setSearchQ(q);
    if (!q.trim()) { setSearchResults([]); return; }
    const { data } = await supabase.from("profiles")
      .select("id,username,full_name,avatar_url")
      .or(`username.ilike.%${q}%,full_name.ilike.%${q}%`)
      .neq("id", user?.id ?? "")
      .limit(10);
    setSearchResults((data ?? []) as PublicProfile[]);
  };


  return (
    <AssistantShell title="Digital Twin" hint="Your, answering while you rest" accent={ACCENT} icon={<Bot className="h-5 w-5" />}>
      <div className="mb-3 flex gap-1 overflow-x-auto no-scrollbar">
        {(["setup", "routines", "followers", "chat", "inbox"] as const).map((t) => (
          <button key={t} onClick={() => setTab(t)}
            className={`shrink-0 rounded-full px-3.5 py-1.5 text-xs capitalize ${tab === t ? "bg-foreground text-background" : "glass"}`}>
            {t === "chat" ? "Chat any Twin" : t}
          </button>
        ))}
      </div>

      {tab === "setup" && twin && (
        <div className="space-y-3">
          {/* Private availability card — only the user sees this */}
          <div className="glass-strong rounded-3xl p-4 animate-fade-up">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <div className={`flex h-9 w-9 items-center justify-center rounded-full text-white shadow-md ${
                  status?.status === "busy" ? "bg-rose-500" : "bg-emerald-500"}`}>
                  <Activity className="h-4 w-4" />
                </div>
                <div>
                  <div className="text-sm font-semibold">
                    You're {status?.status === "busy" ? "Busy" : "Available"} <span className="ml-1 text-[10px] font-normal text-muted-foreground">(private)</span>
                  </div>
                  <div className="text-[11px] text-muted-foreground">{status?.reason ?? "Detecting…"}</div>
                </div>
              </div>
              <Shield className="h-4 w-4 opacity-50" />
            </div>
            <div className="mt-3 grid grid-cols-3 gap-1.5">
              {(["auto", "available", "busy"] as const).map((m) => (
                <button key={m} onClick={() => setTwin({ ...twin, manual_status: m })}
                  className={`rounded-xl px-2 py-1.5 text-[11px] capitalize transition ${
                    twin.manual_status === m ? "bg-foreground text-background" : "glass"}`}>{m}</button>
              ))}
            </div>
            <p className="mt-2 text-[10px] text-muted-foreground">
 Availability is used privately by your to decide when to auto-reply. It's never shown to other people.
            </p>
          </div>

          <div className="glass-strong rounded-3xl p-4 space-y-3 animate-fade-up">
            <label className="block">
              <div className="mb-1 text-[11px] font-medium text-muted-foreground">Persona prompt</div>
              <textarea rows={4} value={twin.persona_prompt} onChange={(e) => setTwin({ ...twin, persona_prompt: e.target.value })}
                placeholder="Describe your voice, values, favorite phrases…"
                className="w-full resize-none rounded-xl border border-border bg-white/60 px-3 py-2 text-sm outline-none" />
            </label>
            <label className="block">
              <div className="mb-1 text-[11px] font-medium text-muted-foreground">Tone</div>
              <select value={twin.tone} onChange={(e) => setTwin({ ...twin, tone: e.target.value })}
                className="w-full rounded-xl border border-border bg-white/60 px-3 py-2 text-sm">
                {["friendly", "warm", "playful", "professional", "poetic", "witty"].map((t) => <option key={t}>{t}</option>)}
              </select>
            </label>
            <label className="block">
              <div className="mb-1 text-[11px] font-medium text-muted-foreground">Auto-reply label</div>
              <input value={twin.auto_reply_label} onChange={(e) => setTwin({ ...twin, auto_reply_label: e.target.value })}
                className="w-full rounded-xl border border-border bg-white/60 px-3 py-2 text-sm" />
            </label>
            {[
              { k: "is_enabled" as const, label: "Twin enabled" },
              { k: "availability_detection" as const, label: "availability detection" },
              { k: "focus_mode" as const, label: "Focus mode (force Busy)" },
              { k: "auto_reply_dm" as const, label: "Auto-reply DMs when I'm Busy" },
              { k: "allow_public_ask" as const, label: "Followers can chat with my Twin" },
              { k: "allow_twin_to_twin" as const, label: "Let other Twins talk to mine" },
            ].map((row) => (
              <label key={row.k} className="flex items-center justify-between rounded-xl bg-white/50 px-3 py-2 text-sm">
                <span>{row.label}</span>
                <input type="checkbox" checked={!!twin[row.k]} onChange={(e) => setTwin({ ...twin, [row.k]: e.target.checked })} />
              </label>
            ))}

            {/* Busy schedule */}
            <div className="rounded-2xl bg-white/50 p-3">
              <div className="mb-2 text-[11px] font-medium text-muted-foreground">Busy schedule</div>
              <div className="space-y-2">
                {twin.busy_schedule.map((w, i) => (
                  <div key={i} className="flex items-center gap-2">
                    <input value={w.label || ""} onChange={(e) => {
                      const s = [...twin.busy_schedule]; s[i] = { ...w, label: e.target.value }; setTwin({ ...twin, busy_schedule: s });
                    }} placeholder="Label (Meeting, Sleep…)"
                      className="flex-1 rounded-lg border border-border bg-white px-2 py-1 text-xs" />
                    <input type="time" value={w.from || ""} onChange={(e) => {
                      const s = [...twin.busy_schedule]; s[i] = { ...w, from: e.target.value }; setTwin({ ...twin, busy_schedule: s });
                    }} className="rounded-lg border border-border bg-white px-1 py-1 text-xs" />
                    <input type="time" value={w.to || ""} onChange={(e) => {
                      const s = [...twin.busy_schedule]; s[i] = { ...w, to: e.target.value }; setTwin({ ...twin, busy_schedule: s });
                    }} className="rounded-lg border border-border bg-white px-1 py-1 text-xs" />
                    <button onClick={() => setTwin({ ...twin, busy_schedule: twin.busy_schedule.filter((_, j) => j !== i) })}>
                      <Trash2 className="h-4 w-4 opacity-60" />
                    </button>
                  </div>
                ))}
                <button onClick={() => setTwin({ ...twin, busy_schedule: [...twin.busy_schedule, { label: "", from: "09:00", to: "17:00" }] })}
                  className="flex w-full items-center justify-center gap-1 rounded-lg border border-dashed border-border py-1.5 text-[11px] text-muted-foreground">
                  <Plus className="h-3 w-3" /> Add busy window
                </button>
              </div>
            </div>

            <button onClick={save} disabled={saving}
              className="flex h-11 w-full items-center justify-center gap-2 rounded-full text-sm font-medium text-white shadow-md active:scale-[0.98]"
              style={{ background: ACCENT }}>
              <Save className="h-4 w-4" /> {saving ? "Saving…" : "Save Twin"}
            </button>
          </div>
        </div>
      )}


      {tab === "routines" && (
        <div className="space-y-3">
          <div className="glass rounded-3xl p-3 space-y-2">
            <input value={newR.title} onChange={(e) => setNewR({ ...newR, title: e.target.value })} placeholder="Routine name (e.g. Morning)"
              className="w-full rounded-xl border border-border bg-white/60 px-3 py-2 text-sm" />
            <input value={newR.schedule} onChange={(e) => setNewR({ ...newR, schedule: e.target.value })} placeholder="When (e.g. Weekdays 7–9am)"
              className="w-full rounded-xl border border-border bg-white/60 px-3 py-2 text-sm" />
            <textarea rows={3} value={newR.instructions} onChange={(e) => setNewR({ ...newR, instructions: e.target.value })}
              placeholder="What the Twin should know or answer during this time…"
              className="w-full resize-none rounded-xl border border-border bg-white/60 px-3 py-2 text-sm" />
            <button onClick={addRoutine} className="flex w-full items-center justify-center gap-2 rounded-xl bg-foreground py-2 text-sm text-background">
              <Plus className="h-4 w-4" /> Add routine
            </button>
          </div>
          <ul className="space-y-2">
            {routines.length === 0 && <li className="py-6 text-center text-[11px] text-muted-foreground">No routines yet.</li>}
            {routines.map((r) => (
              <li key={r.id} className="glass rounded-2xl p-3 text-sm">
                <div className="flex items-start justify-between gap-2">
                  <div>
                    <div className="font-medium">{r.title}</div>
                    {r.schedule && <div className="text-[10px] text-muted-foreground">{r.schedule}</div>}
                    <div className="mt-1 whitespace-pre-wrap text-xs">{r.instructions}</div>
                  </div>
                  <button onClick={() => delRoutine(r.id)}><Trash2 className="h-4 w-4 opacity-60" /></button>
                </div>
              </li>
            ))}
          </ul>
        </div>
      )}

      {tab === "followers" && (
        <ul className="space-y-2">
          {followers.length === 0 && <li className="py-6 text-center text-[11px] text-muted-foreground">No followers yet.</li>}
          {followers.map((f) => (
            <li key={f.id} className="glass flex items-center gap-3 rounded-2xl p-3">
              <img src={f.avatar_url || "/favicon.ico"} alt="" className="h-10 w-10 rounded-full object-cover" />
              <div className="flex-1">
                <div className="text-sm font-medium">{f.full_name || f.username}</div>
                <div className="text-[11px] text-muted-foreground">@{f.username}</div>
              </div>
              <Link to="/twin/$userId" params={{ userId: f.id }}
                className="rounded-full px-3 py-1.5 text-[11px] text-white" style={{ background: ACCENT }}>
                <MessageCircle className="mr-1 inline h-3 w-3" /> Chat
              </Link>
            </li>
          ))}
        </ul>
      )}

      {tab === "chat" && (
        <div className="space-y-3">
          <div className="glass flex items-center gap-2 rounded-full p-1.5">
            <Search className="ml-2 h-4 w-4 opacity-60" />
            <input value={searchQ} onChange={(e) => runSearch(e.target.value)}
              placeholder="Find any user by name or @handle"
              className="flex-1 bg-transparent px-2 py-2 text-sm outline-none" />
          </div>
          <ul className="space-y-2">
            {searchQ && searchResults.length === 0 && (
              <li className="py-6 text-center text-[11px] text-muted-foreground">No users found.</li>
            )}
            {!searchQ && (
              <li className="py-6 text-center text-[11px] text-muted-foreground">
 Search a username to chat with their Twin— even if they're offline.
              </li>
            )}
            {searchResults.map((f) => (
              <li key={f.id} className="glass flex items-center gap-3 rounded-2xl p-3">
                <img src={f.avatar_url || "/favicon.ico"} alt="" className="h-10 w-10 rounded-full object-cover" />
                <div className="flex-1">
                  <div className="text-sm font-medium">{f.full_name || f.username}</div>
                  <div className="text-[11px] text-muted-foreground">@{f.username}</div>
                </div>
                <Link to="/twin/$userId" params={{ userId: f.id }}
                  className="rounded-full px-3 py-1.5 text-[11px] text-white" style={{ background: ACCENT }}>
                  <Bot className="mr-1 inline h-3 w-3" /> Talk to Twin
                </Link>
              </li>
            ))}
          </ul>
        </div>
      )}


      {tab === "inbox" && (
        <ul className="space-y-2">
          {convos.length === 0 && <li className="py-6 text-center text-[11px] text-muted-foreground">No Twin conversations yet.</li>}
          {convos.map((c) => {
            const target = c.target_user_id === user?.id ? c.initiator_id : c.target_user_id;
            return (
              <li key={c.id}>
                <Link to="/twin/$userId" params={{ userId: target }} search={{ convo: c.id }}
                  className="glass flex items-center gap-3 rounded-2xl p-3">
                  <div className="flex h-9 w-9 items-center justify-center rounded-full text-white" style={{ background: ACCENT }}>
                    {c.kind === "twin_to_twin" ? <Radio className="h-4 w-4" /> : <MessageCircle className="h-4 w-4" />}
                  </div>
                  <div className="flex-1">
                    <div className="text-sm">{c.title || (c.kind === "twin_to_twin" ? "Twin ↔ Twin" : "Twin chat")}</div>
                    <div className="text-[10px] text-muted-foreground">{c.kind.replace(/_/g, " ")} · {new Date(c.updated_at).toLocaleString()}</div>
                  </div>
                </Link>
              </li>
            );
          })}
        </ul>
      )}
    </AssistantShell>
  );
}
