/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AssistantsRouteImport } from './routes/assistants'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CareerRouteImport } from './routes/career'
import { Route as ChildSafetyRouteImport } from './routes/child-safety'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as CreateRouteImport } from './routes/create'
import { Route as EduReelsRouteImport } from './routes/edu-reels'
import { Route as EducationRouteImport } from './routes/education'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as FutureRouteImport } from './routes/future'
import { Route as HealthRouteImport } from './routes/health'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as KnowledgeFeedRouteImport } from './routes/knowledge-feed'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as NewsRouteImport } from './routes/news'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrbitRouteImport } from './routes/orbit'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SamRouteImport } from './routes/sam'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TranslateRouteImport } from './routes/translate'
import { Route as TravelRouteImport } from './routes/travel'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AdminEduReviewRouteImport } from './routes/admin.edu-review'
import { Route as AgentIndexRouteImport } from './routes/agent.index'
import { Route as AgentActivityRouteImport } from './routes/agent.activity'
import { Route as AgentMemoryRouteImport } from './routes/agent.memory'
import { Route as AgentPermissionsRouteImport } from './routes/agent.permissions'
import { Route as AgentUltraRouteImport } from './routes/agent.ultra'
import { Route as ApiSamRouteImport } from './routes/api/sam'
import { Route as ApiSmartReplyRouteImport } from './routes/api/smart-reply'
import { Route as ApiWelcomeVoiceRouteImport } from './routes/api/welcome-voice'
import { Route as AssistantsIndexRouteImport } from './routes/assistants.index'
import { Route as AssistantsToolRouteImport } from './routes/assistants.$tool'
import { Route as AssistantsContentCreatorRouteImport } from './routes/assistants.content-creator'
import { Route as AssistantsDigitalTwinRouteImport } from './routes/assistants.digital-twin'
import { Route as AssistantsEmailRouteImport } from './routes/assistants.email'
import { Route as AssistantsScheduleRouteImport } from './routes/assistants.schedule'
import { Route as AssistantsSmartReplyRouteImport } from './routes/assistants.smart-reply'
import { Route as CareerIndexRouteImport } from './routes/career.index'
import { Route as CareerAiRouteImport } from './routes/career.ai'
import { Route as CareerAiCareerRouteImport } from './routes/career.ai-career'
import { Route as CareerApplicationsRouteImport } from './routes/career.applications'
import { Route as CareerBusinessRouteImport } from './routes/career.business'
import { Route as CareerCompaniesRouteImport } from './routes/career.companies'
import { Route as CareerEventsRouteImport } from './routes/career.events'
import { Route as CareerFeedRouteImport } from './routes/career.feed'
import { Route as CareerHubRouteImport } from './routes/career.hub'
import { Route as CareerJobsRouteImport } from './routes/career.jobs'
import { Route as CareerPortfolioRouteImport } from './routes/career.portfolio'
import { Route as CareerProfileRouteImport } from './routes/career.profile'
import { Route as CareerRecruiterRouteImport } from './routes/career.recruiter'
import { Route as CommunitiesIndexRouteImport } from './routes/communities.index'
import { Route as CommunitiesSlugRouteImport } from './routes/communities.$slug'
import { Route as CommunitiesNewRouteImport } from './routes/communities.new'
import { Route as EduReelsNewRouteImport } from './routes/edu-reels.new'
import { Route as EducationIndexRouteImport } from './routes/education.index'
import { Route as EducationCatKeyRouteImport } from './routes/education.$catKey'
import { Route as EducationJeeCoachRouteImport } from './routes/education.jee-coach'
import { Route as KnowledgeFeedPostIdRouteImport } from './routes/knowledge-feed.$postId'
import { Route as KnowledgeFeedNewRouteImport } from './routes/knowledge-feed.new'
import { Route as MessagesChatIdRouteImport } from './routes/messages.$chatId'
import { Route as OrbitIndexRouteImport } from './routes/orbit.index'
import { Route as OrbitPostIdRouteImport } from './routes/orbit.$postId'
import { Route as OrbitExploreRouteImport } from './routes/orbit.explore'
import { Route as OrbitMessagesRouteImport } from './routes/orbit.messages'
import { Route as OrbitNotificationsRouteImport } from './routes/orbit.notifications'
import { Route as OrbitPodcastsRouteImport } from './routes/orbit.podcasts'
import { Route as OrbitProfileRouteImport } from './routes/orbit.profile'
import { Route as OrbitReelsRouteImport } from './routes/orbit.reels'
import { Route as OrbitSetupRouteImport } from './routes/orbit.setup'
import { Route as PPostIdRouteImport } from './routes/p.$postId'
import { Route as PremiumCareerRouteImport } from './routes/premium.career'
import { Route as PremiumCreatorRouteImport } from './routes/premium.creator'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsDeleteAccountRouteImport } from './routes/settings.delete-account'
import { Route as SettingsPrivacyRouteImport } from './routes/settings.privacy'
import { Route as TwinUserIdRouteImport } from './routes/twin.$userId'
import { Route as ApiAgentPlanRouteImport } from './routes/api/agent.plan'
import { Route as ApiCareerJobSuggestRouteImport } from './routes/api/career.job-suggest'
import { Route as ApiCareerResumeMatchRouteImport } from './routes/api/career.resume-match'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as ApiSamImageRouteImport } from './routes/api/sam.image'
import { Route as CareerBusinessOppIdRouteImport } from './routes/career.business.$oppId'
import { Route as CareerBusinessNewRouteImport } from './routes/career.business.new'
import { Route as CareerJobsJobIdRouteImport } from './routes/career.jobs.$jobId'
import { Route as CareerJobsNewRouteImport } from './routes/career.jobs.new'
import { Route as CareerReelsNewRouteImport } from './routes/career.reels.new'
import { Route as EducationCatKeyIndexRouteImport } from './routes/education.$catKey.index'
import { Route as EducationCatKeySubKeyRouteImport } from './routes/education.$catKey.$subKey'
import { Route as EducationJeeToolKeyRouteImport } from './routes/education.jee.$toolKey'
import { Route as EducationJeeLevelsRouteImport } from './routes/education.jee.levels'
import { Route as EducationNeetToolKeyRouteImport } from './routes/education.neet.$toolKey'
import { Route as EducationStudyIndexRouteImport } from './routes/education.study.index'
import { Route as EducationStudyExamRouteImport } from './routes/education.study.$exam'
import { Route as OrbitCSlugRouteImport } from './routes/orbit.c.$slug'
import { Route as OrbitProjectsIndexRouteImport } from './routes/orbit.projects.index'
import { Route as OrbitProjectsProjectIdRouteImport } from './routes/orbit.projects.$projectId'
import { Route as OrbitProjectsNewRouteImport } from './routes/orbit.projects.new'
import { Route as ApiPublicOgPostPostIdRouteImport } from './routes/api/public/og/post/$postId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantsRoute = AssistantsRouteImport.update({
  id: '/assistants',
  path: '/assistants',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildSafetyRoute = ChildSafetyRouteImport.update({
  id: '/child-safety',
  path: '/child-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EduReelsRoute = EduReelsRouteImport.update({
  id: '/edu-reels',
  path: '/edu-reels',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureRoute = FutureRouteImport.update({
  id: '/future',
  path: '/future',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeFeedRoute = KnowledgeFeedRouteImport.update({
  id: '/knowledge-feed',
  path: '/knowledge-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrbitRoute = OrbitRouteImport.update({
  id: '/orbit',
  path: '/orbit',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SamRoute = SamRouteImport.update({
  id: '/sam',
  path: '/sam',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslateRoute = TranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelRoute = TravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEduReviewRoute = AdminEduReviewRouteImport.update({
  id: '/admin/edu-review',
  path: '/admin/edu-review',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentRoute,
} as any)
const AgentActivityRoute = AgentActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AgentRoute,
} as any)
const AgentMemoryRoute = AgentMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AgentRoute,
} as any)
const AgentPermissionsRoute = AgentPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AgentRoute,
} as any)
const AgentUltraRoute = AgentUltraRouteImport.update({
  id: '/ultra',
  path: '/ultra',
  getParentRoute: () => AgentRoute,
} as any)
const ApiSamRoute = ApiSamRouteImport.update({
  id: '/api/sam',
  path: '/api/sam',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmartReplyRoute = ApiSmartReplyRouteImport.update({
  id: '/api/smart-reply',
  path: '/api/smart-reply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWelcomeVoiceRoute = ApiWelcomeVoiceRouteImport.update({
  id: '/api/welcome-voice',
  path: '/api/welcome-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantsIndexRoute = AssistantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssistantsRoute,
} as any)
const AssistantsToolRoute = AssistantsToolRouteImport.update({
  id: '/$tool',
  path: '/$tool',
  getParentRoute: () => AssistantsRoute,
} as any)
const AssistantsContentCreatorRoute =
  AssistantsContentCreatorRouteImport.update({
    id: '/content-creator',
    path: '/content-creator',
    getParentRoute: () => AssistantsRoute,
  } as any)
const AssistantsDigitalTwinRoute = AssistantsDigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => AssistantsRoute,
} as any)
const AssistantsEmailRoute = AssistantsEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AssistantsRoute,
} as any)
const AssistantsScheduleRoute = AssistantsScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AssistantsRoute,
} as any)
const AssistantsSmartReplyRoute = AssistantsSmartReplyRouteImport.update({
  id: '/smart-reply',
  path: '/smart-reply',
  getParentRoute: () => AssistantsRoute,
} as any)
const CareerIndexRoute = CareerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareerRoute,
} as any)
const CareerAiRoute = CareerAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => CareerRoute,
} as any)
const CareerAiCareerRoute = CareerAiCareerRouteImport.update({
  id: '/ai-career',
  path: '/ai-career',
  getParentRoute: () => CareerRoute,
} as any)
const CareerApplicationsRoute = CareerApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => CareerRoute,
} as any)
const CareerBusinessRoute = CareerBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => CareerRoute,
} as any)
const CareerCompaniesRoute = CareerCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => CareerRoute,
} as any)
const CareerEventsRoute = CareerEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => CareerRoute,
} as any)
const CareerFeedRoute = CareerFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => CareerRoute,
} as any)
const CareerHubRoute = CareerHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => CareerRoute,
} as any)
const CareerJobsRoute = CareerJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => CareerRoute,
} as any)
const CareerPortfolioRoute = CareerPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => CareerRoute,
} as any)
const CareerProfileRoute = CareerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CareerRoute,
} as any)
const CareerRecruiterRoute = CareerRecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => CareerRoute,
} as any)
const CommunitiesIndexRoute = CommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesSlugRoute = CommunitiesSlugRouteImport.update({
  id: '/communities/$slug',
  path: '/communities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesNewRoute = CommunitiesNewRouteImport.update({
  id: '/communities/new',
  path: '/communities/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EduReelsNewRoute = EduReelsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EduReelsRoute,
} as any)
const EducationIndexRoute = EducationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EducationRoute,
} as any)
const EducationCatKeyRoute = EducationCatKeyRouteImport.update({
  id: '/$catKey',
  path: '/$catKey',
  getParentRoute: () => EducationRoute,
} as any)
const EducationJeeCoachRoute = EducationJeeCoachRouteImport.update({
  id: '/jee-coach',
  path: '/jee-coach',
  getParentRoute: () => EducationRoute,
} as any)
const KnowledgeFeedPostIdRoute = KnowledgeFeedPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => KnowledgeFeedRoute,
} as any)
const KnowledgeFeedNewRoute = KnowledgeFeedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => KnowledgeFeedRoute,
} as any)
const MessagesChatIdRoute = MessagesChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => MessagesRoute,
} as any)
const OrbitIndexRoute = OrbitIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrbitRoute,
} as any)
const OrbitPostIdRoute = OrbitPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => OrbitRoute,
} as any)
const OrbitExploreRoute = OrbitExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => OrbitRoute,
} as any)
const OrbitMessagesRoute = OrbitMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => OrbitRoute,
} as any)
const OrbitNotificationsRoute = OrbitNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => OrbitRoute,
} as any)
const OrbitPodcastsRoute = OrbitPodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => OrbitRoute,
} as any)
const OrbitProfileRoute = OrbitProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OrbitRoute,
} as any)
const OrbitReelsRoute = OrbitReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => OrbitRoute,
} as any)
const OrbitSetupRoute = OrbitSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => OrbitRoute,
} as any)
const PPostIdRoute = PPostIdRouteImport.update({
  id: '/p/$postId',
  path: '/p/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumCareerRoute = PremiumCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => PremiumRoute,
} as any)
const PremiumCreatorRoute = PremiumCreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => PremiumRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDeleteAccountRoute = SettingsDeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SettingsRoute,
} as any)
const TwinUserIdRoute = TwinUserIdRouteImport.update({
  id: '/twin/$userId',
  path: '/twin/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentPlanRoute = ApiAgentPlanRouteImport.update({
  id: '/api/agent/plan',
  path: '/api/agent/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCareerJobSuggestRoute = ApiCareerJobSuggestRouteImport.update({
  id: '/api/career/job-suggest',
  path: '/api/career/job-suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCareerResumeMatchRoute = ApiCareerResumeMatchRouteImport.update({
  id: '/api/career/resume-match',
  path: '/api/career/resume-match',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSamImageRoute = ApiSamImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => ApiSamRoute,
} as any)
const CareerBusinessOppIdRoute = CareerBusinessOppIdRouteImport.update({
  id: '/$oppId',
  path: '/$oppId',
  getParentRoute: () => CareerBusinessRoute,
} as any)
const CareerBusinessNewRoute = CareerBusinessNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CareerBusinessRoute,
} as any)
const CareerJobsJobIdRoute = CareerJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => CareerJobsRoute,
} as any)
const CareerJobsNewRoute = CareerJobsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CareerJobsRoute,
} as any)
const CareerReelsNewRoute = CareerReelsNewRouteImport.update({
  id: '/reels/new',
  path: '/reels/new',
  getParentRoute: () => CareerRoute,
} as any)
const EducationCatKeyIndexRoute = EducationCatKeyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EducationCatKeyRoute,
} as any)
const EducationCatKeySubKeyRoute = EducationCatKeySubKeyRouteImport.update({
  id: '/$subKey',
  path: '/$subKey',
  getParentRoute: () => EducationCatKeyRoute,
} as any)
const EducationJeeToolKeyRoute = EducationJeeToolKeyRouteImport.update({
  id: '/jee/$toolKey',
  path: '/jee/$toolKey',
  getParentRoute: () => EducationRoute,
} as any)
const EducationJeeLevelsRoute = EducationJeeLevelsRouteImport.update({
  id: '/jee/levels',
  path: '/jee/levels',
  getParentRoute: () => EducationRoute,
} as any)
const EducationNeetToolKeyRoute = EducationNeetToolKeyRouteImport.update({
  id: '/neet/$toolKey',
  path: '/neet/$toolKey',
  getParentRoute: () => EducationRoute,
} as any)
const EducationStudyIndexRoute = EducationStudyIndexRouteImport.update({
  id: '/study/',
  path: '/study/',
  getParentRoute: () => EducationRoute,
} as any)
const EducationStudyExamRoute = EducationStudyExamRouteImport.update({
  id: '/study/$exam',
  path: '/study/$exam',
  getParentRoute: () => EducationRoute,
} as any)
const OrbitCSlugRoute = OrbitCSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => OrbitRoute,
} as any)
const OrbitProjectsIndexRoute = OrbitProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => OrbitRoute,
} as any)
const OrbitProjectsProjectIdRoute = OrbitProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => OrbitRoute,
} as any)
const OrbitProjectsNewRoute = OrbitProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => OrbitRoute,
} as any)
const ApiPublicOgPostPostIdRoute = ApiPublicOgPostPostIdRouteImport.update({
  id: '/api/public/og/post/$postId',
  path: '/api/public/og/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRouteWithChildren
  '/assistants': typeof AssistantsRouteWithChildren
  '/auth': typeof AuthRoute
  '/career': typeof CareerRouteWithChildren
  '/child-safety': typeof ChildSafetyRoute
  '/connections': typeof ConnectionsRoute
  '/create': typeof CreateRoute
  '/edu-reels': typeof EduReelsRouteWithChildren
  '/education': typeof EducationRouteWithChildren
  '/explore': typeof ExploreRoute
  '/finance': typeof FinanceRoute
  '/future': typeof FutureRoute
  '/health': typeof HealthRoute
  '/knowledge': typeof KnowledgeRoute
  '/knowledge-feed': typeof KnowledgeFeedRouteWithChildren
  '/learn': typeof LearnRoute
  '/memory': typeof MemoryRoute
  '/messages': typeof MessagesRouteWithChildren
  '/moderation': typeof ModerationRoute
  '/news': typeof NewsRoute
  '/notifications': typeof NotificationsRoute
  '/orbit': typeof OrbitRouteWithChildren
  '/premium': typeof PremiumRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reels': typeof ReelsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sam': typeof SamRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/shopping': typeof ShoppingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/translate': typeof TranslateRoute
  '/travel': typeof TravelRoute
  '/welcome': typeof WelcomeRoute
  '/admin/edu-review': typeof AdminEduReviewRoute
  '/agent/activity': typeof AgentActivityRoute
  '/agent/memory': typeof AgentMemoryRoute
  '/agent/permissions': typeof AgentPermissionsRoute
  '/agent/ultra': typeof AgentUltraRoute
  '/api/sam': typeof ApiSamRouteWithChildren
  '/api/smart-reply': typeof ApiSmartReplyRoute
  '/api/welcome-voice': typeof ApiWelcomeVoiceRoute
  '/assistants/$tool': typeof AssistantsToolRoute
  '/assistants/content-creator': typeof AssistantsContentCreatorRoute
  '/assistants/digital-twin': typeof AssistantsDigitalTwinRoute
  '/assistants/email': typeof AssistantsEmailRoute
  '/assistants/schedule': typeof AssistantsScheduleRoute
  '/assistants/smart-reply': typeof AssistantsSmartReplyRoute
  '/career/ai': typeof CareerAiRoute
  '/career/ai-career': typeof CareerAiCareerRoute
  '/career/applications': typeof CareerApplicationsRoute
  '/career/business': typeof CareerBusinessRouteWithChildren
  '/career/companies': typeof CareerCompaniesRoute
  '/career/events': typeof CareerEventsRoute
  '/career/feed': typeof CareerFeedRoute
  '/career/hub': typeof CareerHubRoute
  '/career/jobs': typeof CareerJobsRouteWithChildren
  '/career/portfolio': typeof CareerPortfolioRoute
  '/career/profile': typeof CareerProfileRoute
  '/career/recruiter': typeof CareerRecruiterRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/communities/new': typeof CommunitiesNewRoute
  '/edu-reels/new': typeof EduReelsNewRoute
  '/education/$catKey': typeof EducationCatKeyRouteWithChildren
  '/education/jee-coach': typeof EducationJeeCoachRoute
  '/knowledge-feed/$postId': typeof KnowledgeFeedPostIdRoute
  '/knowledge-feed/new': typeof KnowledgeFeedNewRoute
  '/messages/$chatId': typeof MessagesChatIdRoute
  '/orbit/$postId': typeof OrbitPostIdRoute
  '/orbit/explore': typeof OrbitExploreRoute
  '/orbit/messages': typeof OrbitMessagesRoute
  '/orbit/notifications': typeof OrbitNotificationsRoute
  '/orbit/podcasts': typeof OrbitPodcastsRoute
  '/orbit/profile': typeof OrbitProfileRoute
  '/orbit/reels': typeof OrbitReelsRoute
  '/orbit/setup': typeof OrbitSetupRoute
  '/p/$postId': typeof PPostIdRoute
  '/premium/career': typeof PremiumCareerRoute
  '/premium/creator': typeof PremiumCreatorRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/settings/delete-account': typeof SettingsDeleteAccountRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/twin/$userId': typeof TwinUserIdRoute
  '/agent/': typeof AgentIndexRoute
  '/assistants/': typeof AssistantsIndexRoute
  '/career/': typeof CareerIndexRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/education/': typeof EducationIndexRoute
  '/orbit/': typeof OrbitIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/agent/plan': typeof ApiAgentPlanRoute
  '/api/career/job-suggest': typeof ApiCareerJobSuggestRoute
  '/api/career/resume-match': typeof ApiCareerResumeMatchRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/sam/image': typeof ApiSamImageRoute
  '/career/business/$oppId': typeof CareerBusinessOppIdRoute
  '/career/business/new': typeof CareerBusinessNewRoute
  '/career/jobs/$jobId': typeof CareerJobsJobIdRoute
  '/career/jobs/new': typeof CareerJobsNewRoute
  '/career/reels/new': typeof CareerReelsNewRoute
  '/education/$catKey/$subKey': typeof EducationCatKeySubKeyRoute
  '/education/jee/$toolKey': typeof EducationJeeToolKeyRoute
  '/education/jee/levels': typeof EducationJeeLevelsRoute
  '/education/neet/$toolKey': typeof EducationNeetToolKeyRoute
  '/education/study/$exam': typeof EducationStudyExamRoute
  '/orbit/c/$slug': typeof OrbitCSlugRoute
  '/orbit/projects/$projectId': typeof OrbitProjectsProjectIdRoute
  '/orbit/projects/new': typeof OrbitProjectsNewRoute
  '/education/$catKey/': typeof EducationCatKeyIndexRoute
  '/education/study/': typeof EducationStudyIndexRoute
  '/orbit/projects/': typeof OrbitProjectsIndexRoute
  '/api/public/og/post/$postId': typeof ApiPublicOgPostPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/child-safety': typeof ChildSafetyRoute
  '/connections': typeof ConnectionsRoute
  '/create': typeof CreateRoute
  '/edu-reels': typeof EduReelsRouteWithChildren
  '/explore': typeof ExploreRoute
  '/finance': typeof FinanceRoute
  '/future': typeof FutureRoute
  '/health': typeof HealthRoute
  '/knowledge': typeof KnowledgeRoute
  '/knowledge-feed': typeof KnowledgeFeedRouteWithChildren
  '/learn': typeof LearnRoute
  '/memory': typeof MemoryRoute
  '/messages': typeof MessagesRouteWithChildren
  '/moderation': typeof ModerationRoute
  '/news': typeof NewsRoute
  '/notifications': typeof NotificationsRoute
  '/premium': typeof PremiumRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reels': typeof ReelsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sam': typeof SamRoute
  '/search': typeof SearchRoute
  '/shopping': typeof ShoppingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/translate': typeof TranslateRoute
  '/travel': typeof TravelRoute
  '/welcome': typeof WelcomeRoute
  '/admin/edu-review': typeof AdminEduReviewRoute
  '/agent/activity': typeof AgentActivityRoute
  '/agent/memory': typeof AgentMemoryRoute
  '/agent/permissions': typeof AgentPermissionsRoute
  '/agent/ultra': typeof AgentUltraRoute
  '/api/sam': typeof ApiSamRouteWithChildren
  '/api/smart-reply': typeof ApiSmartReplyRoute
  '/api/welcome-voice': typeof ApiWelcomeVoiceRoute
  '/assistants/$tool': typeof AssistantsToolRoute
  '/assistants/content-creator': typeof AssistantsContentCreatorRoute
  '/assistants/digital-twin': typeof AssistantsDigitalTwinRoute
  '/assistants/email': typeof AssistantsEmailRoute
  '/assistants/schedule': typeof AssistantsScheduleRoute
  '/assistants/smart-reply': typeof AssistantsSmartReplyRoute
  '/career/ai': typeof CareerAiRoute
  '/career/ai-career': typeof CareerAiCareerRoute
  '/career/applications': typeof CareerApplicationsRoute
  '/career/business': typeof CareerBusinessRouteWithChildren
  '/career/companies': typeof CareerCompaniesRoute
  '/career/events': typeof CareerEventsRoute
  '/career/feed': typeof CareerFeedRoute
  '/career/hub': typeof CareerHubRoute
  '/career/jobs': typeof CareerJobsRouteWithChildren
  '/career/portfolio': typeof CareerPortfolioRoute
  '/career/profile': typeof CareerProfileRoute
  '/career/recruiter': typeof CareerRecruiterRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/communities/new': typeof CommunitiesNewRoute
  '/edu-reels/new': typeof EduReelsNewRoute
  '/education/jee-coach': typeof EducationJeeCoachRoute
  '/knowledge-feed/$postId': typeof KnowledgeFeedPostIdRoute
  '/knowledge-feed/new': typeof KnowledgeFeedNewRoute
  '/messages/$chatId': typeof MessagesChatIdRoute
  '/orbit/$postId': typeof OrbitPostIdRoute
  '/orbit/explore': typeof OrbitExploreRoute
  '/orbit/messages': typeof OrbitMessagesRoute
  '/orbit/notifications': typeof OrbitNotificationsRoute
  '/orbit/podcasts': typeof OrbitPodcastsRoute
  '/orbit/profile': typeof OrbitProfileRoute
  '/orbit/reels': typeof OrbitReelsRoute
  '/orbit/setup': typeof OrbitSetupRoute
  '/p/$postId': typeof PPostIdRoute
  '/premium/career': typeof PremiumCareerRoute
  '/premium/creator': typeof PremiumCreatorRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/settings/delete-account': typeof SettingsDeleteAccountRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/twin/$userId': typeof TwinUserIdRoute
  '/agent': typeof AgentIndexRoute
  '/assistants': typeof AssistantsIndexRoute
  '/career': typeof CareerIndexRoute
  '/communities': typeof CommunitiesIndexRoute
  '/education': typeof EducationIndexRoute
  '/orbit': typeof OrbitIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/agent/plan': typeof ApiAgentPlanRoute
  '/api/career/job-suggest': typeof ApiCareerJobSuggestRoute
  '/api/career/resume-match': typeof ApiCareerResumeMatchRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/sam/image': typeof ApiSamImageRoute
  '/career/business/$oppId': typeof CareerBusinessOppIdRoute
  '/career/business/new': typeof CareerBusinessNewRoute
  '/career/jobs/$jobId': typeof CareerJobsJobIdRoute
  '/career/jobs/new': typeof CareerJobsNewRoute
  '/career/reels/new': typeof CareerReelsNewRoute
  '/education/$catKey/$subKey': typeof EducationCatKeySubKeyRoute
  '/education/jee/$toolKey': typeof EducationJeeToolKeyRoute
  '/education/jee/levels': typeof EducationJeeLevelsRoute
  '/education/neet/$toolKey': typeof EducationNeetToolKeyRoute
  '/education/study/$exam': typeof EducationStudyExamRoute
  '/orbit/c/$slug': typeof OrbitCSlugRoute
  '/orbit/projects/$projectId': typeof OrbitProjectsProjectIdRoute
  '/orbit/projects/new': typeof OrbitProjectsNewRoute
  '/education/$catKey': typeof EducationCatKeyIndexRoute
  '/education/study': typeof EducationStudyIndexRoute
  '/orbit/projects': typeof OrbitProjectsIndexRoute
  '/api/public/og/post/$postId': typeof ApiPublicOgPostPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRouteWithChildren
  '/assistants': typeof AssistantsRouteWithChildren
  '/auth': typeof AuthRoute
  '/career': typeof CareerRouteWithChildren
  '/child-safety': typeof ChildSafetyRoute
  '/connections': typeof ConnectionsRoute
  '/create': typeof CreateRoute
  '/edu-reels': typeof EduReelsRouteWithChildren
  '/education': typeof EducationRouteWithChildren
  '/explore': typeof ExploreRoute
  '/finance': typeof FinanceRoute
  '/future': typeof FutureRoute
  '/health': typeof HealthRoute
  '/knowledge': typeof KnowledgeRoute
  '/knowledge-feed': typeof KnowledgeFeedRouteWithChildren
  '/learn': typeof LearnRoute
  '/memory': typeof MemoryRoute
  '/messages': typeof MessagesRouteWithChildren
  '/moderation': typeof ModerationRoute
  '/news': typeof NewsRoute
  '/notifications': typeof NotificationsRoute
  '/orbit': typeof OrbitRouteWithChildren
  '/premium': typeof PremiumRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reels': typeof ReelsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sam': typeof SamRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/shopping': typeof ShoppingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/translate': typeof TranslateRoute
  '/travel': typeof TravelRoute
  '/welcome': typeof WelcomeRoute
  '/admin/edu-review': typeof AdminEduReviewRoute
  '/agent/activity': typeof AgentActivityRoute
  '/agent/memory': typeof AgentMemoryRoute
  '/agent/permissions': typeof AgentPermissionsRoute
  '/agent/ultra': typeof AgentUltraRoute
  '/api/sam': typeof ApiSamRouteWithChildren
  '/api/smart-reply': typeof ApiSmartReplyRoute
  '/api/welcome-voice': typeof ApiWelcomeVoiceRoute
  '/assistants/$tool': typeof AssistantsToolRoute
  '/assistants/content-creator': typeof AssistantsContentCreatorRoute
  '/assistants/digital-twin': typeof AssistantsDigitalTwinRoute
  '/assistants/email': typeof AssistantsEmailRoute
  '/assistants/schedule': typeof AssistantsScheduleRoute
  '/assistants/smart-reply': typeof AssistantsSmartReplyRoute
  '/career/ai': typeof CareerAiRoute
  '/career/ai-career': typeof CareerAiCareerRoute
  '/career/applications': typeof CareerApplicationsRoute
  '/career/business': typeof CareerBusinessRouteWithChildren
  '/career/companies': typeof CareerCompaniesRoute
  '/career/events': typeof CareerEventsRoute
  '/career/feed': typeof CareerFeedRoute
  '/career/hub': typeof CareerHubRoute
  '/career/jobs': typeof CareerJobsRouteWithChildren
  '/career/portfolio': typeof CareerPortfolioRoute
  '/career/profile': typeof CareerProfileRoute
  '/career/recruiter': typeof CareerRecruiterRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/communities/new': typeof CommunitiesNewRoute
  '/edu-reels/new': typeof EduReelsNewRoute
  '/education/$catKey': typeof EducationCatKeyRouteWithChildren
  '/education/jee-coach': typeof EducationJeeCoachRoute
  '/knowledge-feed/$postId': typeof KnowledgeFeedPostIdRoute
  '/knowledge-feed/new': typeof KnowledgeFeedNewRoute
  '/messages/$chatId': typeof MessagesChatIdRoute
  '/orbit/$postId': typeof OrbitPostIdRoute
  '/orbit/explore': typeof OrbitExploreRoute
  '/orbit/messages': typeof OrbitMessagesRoute
  '/orbit/notifications': typeof OrbitNotificationsRoute
  '/orbit/podcasts': typeof OrbitPodcastsRoute
  '/orbit/profile': typeof OrbitProfileRoute
  '/orbit/reels': typeof OrbitReelsRoute
  '/orbit/setup': typeof OrbitSetupRoute
  '/p/$postId': typeof PPostIdRoute
  '/premium/career': typeof PremiumCareerRoute
  '/premium/creator': typeof PremiumCreatorRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/settings/delete-account': typeof SettingsDeleteAccountRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/twin/$userId': typeof TwinUserIdRoute
  '/agent/': typeof AgentIndexRoute
  '/assistants/': typeof AssistantsIndexRoute
  '/career/': typeof CareerIndexRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/education/': typeof EducationIndexRoute
  '/orbit/': typeof OrbitIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/agent/plan': typeof ApiAgentPlanRoute
  '/api/career/job-suggest': typeof ApiCareerJobSuggestRoute
  '/api/career/resume-match': typeof ApiCareerResumeMatchRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/sam/image': typeof ApiSamImageRoute
  '/career/business/$oppId': typeof CareerBusinessOppIdRoute
  '/career/business/new': typeof CareerBusinessNewRoute
  '/career/jobs/$jobId': typeof CareerJobsJobIdRoute
  '/career/jobs/new': typeof CareerJobsNewRoute
  '/career/reels/new': typeof CareerReelsNewRoute
  '/education/$catKey/$subKey': typeof EducationCatKeySubKeyRoute
  '/education/jee/$toolKey': typeof EducationJeeToolKeyRoute
  '/education/jee/levels': typeof EducationJeeLevelsRoute
  '/education/neet/$toolKey': typeof EducationNeetToolKeyRoute
  '/education/study/$exam': typeof EducationStudyExamRoute
  '/orbit/c/$slug': typeof OrbitCSlugRoute
  '/orbit/projects/$projectId': typeof OrbitProjectsProjectIdRoute
  '/orbit/projects/new': typeof OrbitProjectsNewRoute
  '/education/$catKey/': typeof EducationCatKeyIndexRoute
  '/education/study/': typeof EducationStudyIndexRoute
  '/orbit/projects/': typeof OrbitProjectsIndexRoute
  '/api/public/og/post/$postId': typeof ApiPublicOgPostPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/assistants'
    | '/auth'
    | '/career'
    | '/child-safety'
    | '/connections'
    | '/create'
    | '/edu-reels'
    | '/education'
    | '/explore'
    | '/finance'
    | '/future'
    | '/health'
    | '/knowledge'
    | '/knowledge-feed'
    | '/learn'
    | '/memory'
    | '/messages'
    | '/moderation'
    | '/news'
    | '/notifications'
    | '/orbit'
    | '/premium'
    | '/privacy'
    | '/reels'
    | '/reset-password'
    | '/sam'
    | '/search'
    | '/settings'
    | '/shopping'
    | '/sitemap.xml'
    | '/translate'
    | '/travel'
    | '/welcome'
    | '/admin/edu-review'
    | '/agent/activity'
    | '/agent/memory'
    | '/agent/permissions'
    | '/agent/ultra'
    | '/api/sam'
    | '/api/smart-reply'
    | '/api/welcome-voice'
    | '/assistants/$tool'
    | '/assistants/content-creator'
    | '/assistants/digital-twin'
    | '/assistants/email'
    | '/assistants/schedule'
    | '/assistants/smart-reply'
    | '/career/ai'
    | '/career/ai-career'
    | '/career/applications'
    | '/career/business'
    | '/career/companies'
    | '/career/events'
    | '/career/feed'
    | '/career/hub'
    | '/career/jobs'
    | '/career/portfolio'
    | '/career/profile'
    | '/career/recruiter'
    | '/communities/$slug'
    | '/communities/new'
    | '/edu-reels/new'
    | '/education/$catKey'
    | '/education/jee-coach'
    | '/knowledge-feed/$postId'
    | '/knowledge-feed/new'
    | '/messages/$chatId'
    | '/orbit/$postId'
    | '/orbit/explore'
    | '/orbit/messages'
    | '/orbit/notifications'
    | '/orbit/podcasts'
    | '/orbit/profile'
    | '/orbit/reels'
    | '/orbit/setup'
    | '/p/$postId'
    | '/premium/career'
    | '/premium/creator'
    | '/profile/$userId'
    | '/settings/delete-account'
    | '/settings/privacy'
    | '/twin/$userId'
    | '/agent/'
    | '/assistants/'
    | '/career/'
    | '/communities/'
    | '/education/'
    | '/orbit/'
    | '/profile/'
    | '/settings/'
    | '/api/agent/plan'
    | '/api/career/job-suggest'
    | '/api/career/resume-match'
    | '/api/public/razorpay-webhook'
    | '/api/sam/image'
    | '/career/business/$oppId'
    | '/career/business/new'
    | '/career/jobs/$jobId'
    | '/career/jobs/new'
    | '/career/reels/new'
    | '/education/$catKey/$subKey'
    | '/education/jee/$toolKey'
    | '/education/jee/levels'
    | '/education/neet/$toolKey'
    | '/education/study/$exam'
    | '/orbit/c/$slug'
    | '/orbit/projects/$projectId'
    | '/orbit/projects/new'
    | '/education/$catKey/'
    | '/education/study/'
    | '/orbit/projects/'
    | '/api/public/og/post/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/child-safety'
    | '/connections'
    | '/create'
    | '/edu-reels'
    | '/explore'
    | '/finance'
    | '/future'
    | '/health'
    | '/knowledge'
    | '/knowledge-feed'
    | '/learn'
    | '/memory'
    | '/messages'
    | '/moderation'
    | '/news'
    | '/notifications'
    | '/premium'
    | '/privacy'
    | '/reels'
    | '/reset-password'
    | '/sam'
    | '/search'
    | '/shopping'
    | '/sitemap.xml'
    | '/translate'
    | '/travel'
    | '/welcome'
    | '/admin/edu-review'
    | '/agent/activity'
    | '/agent/memory'
    | '/agent/permissions'
    | '/agent/ultra'
    | '/api/sam'
    | '/api/smart-reply'
    | '/api/welcome-voice'
    | '/assistants/$tool'
    | '/assistants/content-creator'
    | '/assistants/digital-twin'
    | '/assistants/email'
    | '/assistants/schedule'
    | '/assistants/smart-reply'
    | '/career/ai'
    | '/career/ai-career'
    | '/career/applications'
    | '/career/business'
    | '/career/companies'
    | '/career/events'
    | '/career/feed'
    | '/career/hub'
    | '/career/jobs'
    | '/career/portfolio'
    | '/career/profile'
    | '/career/recruiter'
    | '/communities/$slug'
    | '/communities/new'
    | '/edu-reels/new'
    | '/education/jee-coach'
    | '/knowledge-feed/$postId'
    | '/knowledge-feed/new'
    | '/messages/$chatId'
    | '/orbit/$postId'
    | '/orbit/explore'
    | '/orbit/messages'
    | '/orbit/notifications'
    | '/orbit/podcasts'
    | '/orbit/profile'
    | '/orbit/reels'
    | '/orbit/setup'
    | '/p/$postId'
    | '/premium/career'
    | '/premium/creator'
    | '/profile/$userId'
    | '/settings/delete-account'
    | '/settings/privacy'
    | '/twin/$userId'
    | '/agent'
    | '/assistants'
    | '/career'
    | '/communities'
    | '/education'
    | '/orbit'
    | '/profile'
    | '/settings'
    | '/api/agent/plan'
    | '/api/career/job-suggest'
    | '/api/career/resume-match'
    | '/api/public/razorpay-webhook'
    | '/api/sam/image'
    | '/career/business/$oppId'
    | '/career/business/new'
    | '/career/jobs/$jobId'
    | '/career/jobs/new'
    | '/career/reels/new'
    | '/education/$catKey/$subKey'
    | '/education/jee/$toolKey'
    | '/education/jee/levels'
    | '/education/neet/$toolKey'
    | '/education/study/$exam'
    | '/orbit/c/$slug'
    | '/orbit/projects/$projectId'
    | '/orbit/projects/new'
    | '/education/$catKey'
    | '/education/study'
    | '/orbit/projects'
    | '/api/public/og/post/$postId'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/assistants'
    | '/auth'
    | '/career'
    | '/child-safety'
    | '/connections'
    | '/create'
    | '/edu-reels'
    | '/education'
    | '/explore'
    | '/finance'
    | '/future'
    | '/health'
    | '/knowledge'
    | '/knowledge-feed'
    | '/learn'
    | '/memory'
    | '/messages'
    | '/moderation'
    | '/news'
    | '/notifications'
    | '/orbit'
    | '/premium'
    | '/privacy'
    | '/reels'
    | '/reset-password'
    | '/sam'
    | '/search'
    | '/settings'
    | '/shopping'
    | '/sitemap.xml'
    | '/translate'
    | '/travel'
    | '/welcome'
    | '/admin/edu-review'
    | '/agent/activity'
    | '/agent/memory'
    | '/agent/permissions'
    | '/agent/ultra'
    | '/api/sam'
    | '/api/smart-reply'
    | '/api/welcome-voice'
    | '/assistants/$tool'
    | '/assistants/content-creator'
    | '/assistants/digital-twin'
    | '/assistants/email'
    | '/assistants/schedule'
    | '/assistants/smart-reply'
    | '/career/ai'
    | '/career/ai-career'
    | '/career/applications'
    | '/career/business'
    | '/career/companies'
    | '/career/events'
    | '/career/feed'
    | '/career/hub'
    | '/career/jobs'
    | '/career/portfolio'
    | '/career/profile'
    | '/career/recruiter'
    | '/communities/$slug'
    | '/communities/new'
    | '/edu-reels/new'
    | '/education/$catKey'
    | '/education/jee-coach'
    | '/knowledge-feed/$postId'
    | '/knowledge-feed/new'
    | '/messages/$chatId'
    | '/orbit/$postId'
    | '/orbit/explore'
    | '/orbit/messages'
    | '/orbit/notifications'
    | '/orbit/podcasts'
    | '/orbit/profile'
    | '/orbit/reels'
    | '/orbit/setup'
    | '/p/$postId'
    | '/premium/career'
    | '/premium/creator'
    | '/profile/$userId'
    | '/settings/delete-account'
    | '/settings/privacy'
    | '/twin/$userId'
    | '/agent/'
    | '/assistants/'
    | '/career/'
    | '/communities/'
    | '/education/'
    | '/orbit/'
    | '/profile/'
    | '/settings/'
    | '/api/agent/plan'
    | '/api/career/job-suggest'
    | '/api/career/resume-match'
    | '/api/public/razorpay-webhook'
    | '/api/sam/image'
    | '/career/business/$oppId'
    | '/career/business/new'
    | '/career/jobs/$jobId'
    | '/career/jobs/new'
    | '/career/reels/new'
    | '/education/$catKey/$subKey'
    | '/education/jee/$toolKey'
    | '/education/jee/levels'
    | '/education/neet/$toolKey'
    | '/education/study/$exam'
    | '/orbit/c/$slug'
    | '/orbit/projects/$projectId'
    | '/orbit/projects/new'
    | '/education/$catKey/'
    | '/education/study/'
    | '/orbit/projects/'
    | '/api/public/og/post/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRouteWithChildren
  AssistantsRoute: typeof AssistantsRouteWithChildren
  AuthRoute: typeof AuthRoute
  CareerRoute: typeof CareerRouteWithChildren
  ChildSafetyRoute: typeof ChildSafetyRoute
  ConnectionsRoute: typeof ConnectionsRoute
  CreateRoute: typeof CreateRoute
  EduReelsRoute: typeof EduReelsRouteWithChildren
  EducationRoute: typeof EducationRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  FinanceRoute: typeof FinanceRoute
  FutureRoute: typeof FutureRoute
  HealthRoute: typeof HealthRoute
  KnowledgeRoute: typeof KnowledgeRoute
  KnowledgeFeedRoute: typeof KnowledgeFeedRouteWithChildren
  LearnRoute: typeof LearnRoute
  MemoryRoute: typeof MemoryRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  ModerationRoute: typeof ModerationRoute
  NewsRoute: typeof NewsRoute
  NotificationsRoute: typeof NotificationsRoute
  OrbitRoute: typeof OrbitRouteWithChildren
  PremiumRoute: typeof PremiumRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ReelsRoute: typeof ReelsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SamRoute: typeof SamRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ShoppingRoute: typeof ShoppingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TranslateRoute: typeof TranslateRoute
  TravelRoute: typeof TravelRoute
  WelcomeRoute: typeof WelcomeRoute
  AdminEduReviewRoute: typeof AdminEduReviewRoute
  ApiSamRoute: typeof ApiSamRouteWithChildren
  ApiSmartReplyRoute: typeof ApiSmartReplyRoute
  ApiWelcomeVoiceRoute: typeof ApiWelcomeVoiceRoute
  CommunitiesSlugRoute: typeof CommunitiesSlugRoute
  CommunitiesNewRoute: typeof CommunitiesNewRoute
  PPostIdRoute: typeof PPostIdRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  TwinUserIdRoute: typeof TwinUserIdRoute
  CommunitiesIndexRoute: typeof CommunitiesIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ApiAgentPlanRoute: typeof ApiAgentPlanRoute
  ApiCareerJobSuggestRoute: typeof ApiCareerJobSuggestRoute
  ApiCareerResumeMatchRoute: typeof ApiCareerResumeMatchRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  ApiPublicOgPostPostIdRoute: typeof ApiPublicOgPostPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistants': {
      id: '/assistants'
      path: '/assistants'
      fullPath: '/assistants'
      preLoaderRoute: typeof AssistantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child-safety': {
      id: '/child-safety'
      path: '/child-safety'
      fullPath: '/child-safety'
      preLoaderRoute: typeof ChildSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edu-reels': {
      id: '/edu-reels'
      path: '/edu-reels'
      fullPath: '/edu-reels'
      preLoaderRoute: typeof EduReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future': {
      id: '/future'
      path: '/future'
      fullPath: '/future'
      preLoaderRoute: typeof FutureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-feed': {
      id: '/knowledge-feed'
      path: '/knowledge-feed'
      fullPath: '/knowledge-feed'
      preLoaderRoute: typeof KnowledgeFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orbit': {
      id: '/orbit'
      path: '/orbit'
      fullPath: '/orbit'
      preLoaderRoute: typeof OrbitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sam': {
      id: '/sam'
      path: '/sam'
      fullPath: '/sam'
      preLoaderRoute: typeof SamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translate': {
      id: '/translate'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof TranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/edu-review': {
      id: '/admin/edu-review'
      path: '/admin/edu-review'
      fullPath: '/admin/edu-review'
      preLoaderRoute: typeof AdminEduReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/activity': {
      id: '/agent/activity'
      path: '/activity'
      fullPath: '/agent/activity'
      preLoaderRoute: typeof AgentActivityRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/memory': {
      id: '/agent/memory'
      path: '/memory'
      fullPath: '/agent/memory'
      preLoaderRoute: typeof AgentMemoryRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/permissions': {
      id: '/agent/permissions'
      path: '/permissions'
      fullPath: '/agent/permissions'
      preLoaderRoute: typeof AgentPermissionsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/ultra': {
      id: '/agent/ultra'
      path: '/ultra'
      fullPath: '/agent/ultra'
      preLoaderRoute: typeof AgentUltraRouteImport
      parentRoute: typeof AgentRoute
    }
    '/api/sam': {
      id: '/api/sam'
      path: '/api/sam'
      fullPath: '/api/sam'
      preLoaderRoute: typeof ApiSamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/smart-reply': {
      id: '/api/smart-reply'
      path: '/api/smart-reply'
      fullPath: '/api/smart-reply'
      preLoaderRoute: typeof ApiSmartReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/welcome-voice': {
      id: '/api/welcome-voice'
      path: '/api/welcome-voice'
      fullPath: '/api/welcome-voice'
      preLoaderRoute: typeof ApiWelcomeVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistants/': {
      id: '/assistants/'
      path: '/'
      fullPath: '/assistants/'
      preLoaderRoute: typeof AssistantsIndexRouteImport
      parentRoute: typeof AssistantsRoute
    }
    '/assistants/$tool': {
      id: '/assistants/$tool'
      path: '/$tool'
      fullPath: '/assistants/$tool'
      preLoaderRoute: typeof AssistantsToolRouteImport
      parentRoute: typeof AssistantsRoute
    }
    '/assistants/content-creator': {
      id: '/assistants/content-creator'
      path: '/content-creator'
      fullPath: '/assistants/content-creator'
      preLoaderRoute: typeof AssistantsContentCreatorRouteImport
      parentRoute: typeof AssistantsRoute
    }
    '/assistants/digital-twin': {
      id: '/assistants/digital-twin'
      path: '/digital-twin'
      fullPath: '/assistants/digital-twin'
      preLoaderRoute: typeof AssistantsDigitalTwinRouteImport
      parentRoute: typeof AssistantsRoute
    }
    '/assistants/email': {
      id: '/assistants/email'
      path: '/email'
      fullPath: '/assistants/email'
      preLoaderRoute: typeof AssistantsEmailRouteImport
      parentRoute: typeof AssistantsRoute
    }
    '/assistants/schedule': {
      id: '/assistants/schedule'
      path: '/schedule'
      fullPath: '/assistants/schedule'
      preLoaderRoute: typeof AssistantsScheduleRouteImport
      parentRoute: typeof AssistantsRoute
    }
    '/assistants/smart-reply': {
      id: '/assistants/smart-reply'
      path: '/smart-reply'
      fullPath: '/assistants/smart-reply'
      preLoaderRoute: typeof AssistantsSmartReplyRouteImport
      parentRoute: typeof AssistantsRoute
    }
    '/career/': {
      id: '/career/'
      path: '/'
      fullPath: '/career/'
      preLoaderRoute: typeof CareerIndexRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/ai': {
      id: '/career/ai'
      path: '/ai'
      fullPath: '/career/ai'
      preLoaderRoute: typeof CareerAiRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/ai-career': {
      id: '/career/ai-career'
      path: '/ai-career'
      fullPath: '/career/ai-career'
      preLoaderRoute: typeof CareerAiCareerRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/applications': {
      id: '/career/applications'
      path: '/applications'
      fullPath: '/career/applications'
      preLoaderRoute: typeof CareerApplicationsRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/business': {
      id: '/career/business'
      path: '/business'
      fullPath: '/career/business'
      preLoaderRoute: typeof CareerBusinessRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/companies': {
      id: '/career/companies'
      path: '/companies'
      fullPath: '/career/companies'
      preLoaderRoute: typeof CareerCompaniesRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/events': {
      id: '/career/events'
      path: '/events'
      fullPath: '/career/events'
      preLoaderRoute: typeof CareerEventsRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/feed': {
      id: '/career/feed'
      path: '/feed'
      fullPath: '/career/feed'
      preLoaderRoute: typeof CareerFeedRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/hub': {
      id: '/career/hub'
      path: '/hub'
      fullPath: '/career/hub'
      preLoaderRoute: typeof CareerHubRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/jobs': {
      id: '/career/jobs'
      path: '/jobs'
      fullPath: '/career/jobs'
      preLoaderRoute: typeof CareerJobsRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/portfolio': {
      id: '/career/portfolio'
      path: '/portfolio'
      fullPath: '/career/portfolio'
      preLoaderRoute: typeof CareerPortfolioRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/profile': {
      id: '/career/profile'
      path: '/profile'
      fullPath: '/career/profile'
      preLoaderRoute: typeof CareerProfileRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/recruiter': {
      id: '/career/recruiter'
      path: '/recruiter'
      fullPath: '/career/recruiter'
      preLoaderRoute: typeof CareerRecruiterRouteImport
      parentRoute: typeof CareerRoute
    }
    '/communities/': {
      id: '/communities/'
      path: '/communities'
      fullPath: '/communities/'
      preLoaderRoute: typeof CommunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/$slug': {
      id: '/communities/$slug'
      path: '/communities/$slug'
      fullPath: '/communities/$slug'
      preLoaderRoute: typeof CommunitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/new': {
      id: '/communities/new'
      path: '/communities/new'
      fullPath: '/communities/new'
      preLoaderRoute: typeof CommunitiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edu-reels/new': {
      id: '/edu-reels/new'
      path: '/new'
      fullPath: '/edu-reels/new'
      preLoaderRoute: typeof EduReelsNewRouteImport
      parentRoute: typeof EduReelsRoute
    }
    '/education/': {
      id: '/education/'
      path: '/'
      fullPath: '/education/'
      preLoaderRoute: typeof EducationIndexRouteImport
      parentRoute: typeof EducationRoute
    }
    '/education/$catKey': {
      id: '/education/$catKey'
      path: '/$catKey'
      fullPath: '/education/$catKey'
      preLoaderRoute: typeof EducationCatKeyRouteImport
      parentRoute: typeof EducationRoute
    }
    '/education/jee-coach': {
      id: '/education/jee-coach'
      path: '/jee-coach'
      fullPath: '/education/jee-coach'
      preLoaderRoute: typeof EducationJeeCoachRouteImport
      parentRoute: typeof EducationRoute
    }
    '/knowledge-feed/$postId': {
      id: '/knowledge-feed/$postId'
      path: '/$postId'
      fullPath: '/knowledge-feed/$postId'
      preLoaderRoute: typeof KnowledgeFeedPostIdRouteImport
      parentRoute: typeof KnowledgeFeedRoute
    }
    '/knowledge-feed/new': {
      id: '/knowledge-feed/new'
      path: '/new'
      fullPath: '/knowledge-feed/new'
      preLoaderRoute: typeof KnowledgeFeedNewRouteImport
      parentRoute: typeof KnowledgeFeedRoute
    }
    '/messages/$chatId': {
      id: '/messages/$chatId'
      path: '/$chatId'
      fullPath: '/messages/$chatId'
      preLoaderRoute: typeof MessagesChatIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/orbit/': {
      id: '/orbit/'
      path: '/'
      fullPath: '/orbit/'
      preLoaderRoute: typeof OrbitIndexRouteImport
      parentRoute: typeof OrbitRoute
    }
    '/orbit/$postId': {
      id: '/orbit/$postId'
      path: '/$postId'
      fullPath: '/orbit/$postId'
      preLoaderRoute: typeof OrbitPostIdRouteImport
      parentRoute: typeof OrbitRoute
    }
    '/orbit/explore': {
      id: '/orbit/explore'
      path: '/explore'
      fullPath: '/orbit/explore'
      preLoaderRoute: typeof OrbitExploreRouteImport
      parentRoute: typeof OrbitRoute
    }
    '/orbit/messages': {
      id: '/orbit/messages'
      path: '/messages'
      fullPath: '/orbit/messages'
      preLoaderRoute: typeof OrbitMessagesRouteImport
      parentRoute: typeof OrbitRoute
    }
    '/orbit/notifications': {
      id: '/orbit/notifications'
      path: '/notifications'
      fullPath: '/orbit/notifications'
      preLoaderRoute: typeof OrbitNotificationsRouteImport
      parentRoute: typeof OrbitRoute
    }
    '/orbit/podcasts': {
      id: '/orbit/podcasts'
      path: '/podcasts'
      fullPath: '/orbit/podcasts'
      preLoaderRoute: typeof OrbitPodcastsRouteImport
      parentRoute: typeof OrbitRoute
    }
    '/orbit/profile': {
      id: '/orbit/profile'
      path: '/profile'
      fullPath: '/orbit/profile'
      preLoaderRoute: typeof OrbitProfileRouteImport
      parentRoute: typeof OrbitRoute
    }
    '/orbit/reels': {
      id: '/orbit/reels'
      path: '/reels'
      fullPath: '/orbit/reels'
      preLoaderRoute: typeof OrbitReelsRouteImport
      parentRoute: typeof OrbitRoute
    }
    '/orbit/setup': {
      id: '/orbit/setup'
      path: '/setup'
      fullPath: '/orbit/setup'
      preLoaderRoute: typeof OrbitSetupRouteImport
      parentRoute: typeof OrbitRoute
    }
    '/p/$postId': {
      id: '/p/$postId'
      path: '/p/$postId'
      fullPath: '/p/$postId'
      preLoaderRoute: typeof PPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium/career': {
      id: '/premium/career'
      path: '/career'
      fullPath: '/premium/career'
      preLoaderRoute: typeof PremiumCareerRouteImport
      parentRoute: typeof PremiumRoute
    }
    '/premium/creator': {
      id: '/premium/creator'
      path: '/creator'
      fullPath: '/premium/creator'
      preLoaderRoute: typeof PremiumCreatorRouteImport
      parentRoute: typeof PremiumRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/delete-account': {
      id: '/settings/delete-account'
      path: '/delete-account'
      fullPath: '/settings/delete-account'
      preLoaderRoute: typeof SettingsDeleteAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/twin/$userId': {
      id: '/twin/$userId'
      path: '/twin/$userId'
      fullPath: '/twin/$userId'
      preLoaderRoute: typeof TwinUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/plan': {
      id: '/api/agent/plan'
      path: '/api/agent/plan'
      fullPath: '/api/agent/plan'
      preLoaderRoute: typeof ApiAgentPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/career/job-suggest': {
      id: '/api/career/job-suggest'
      path: '/api/career/job-suggest'
      fullPath: '/api/career/job-suggest'
      preLoaderRoute: typeof ApiCareerJobSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/career/resume-match': {
      id: '/api/career/resume-match'
      path: '/api/career/resume-match'
      fullPath: '/api/career/resume-match'
      preLoaderRoute: typeof ApiCareerResumeMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sam/image': {
      id: '/api/sam/image'
      path: '/image'
      fullPath: '/api/sam/image'
      preLoaderRoute: typeof ApiSamImageRouteImport
      parentRoute: typeof ApiSamRoute
    }
    '/career/business/$oppId': {
      id: '/career/business/$oppId'
      path: '/$oppId'
      fullPath: '/career/business/$oppId'
      preLoaderRoute: typeof CareerBusinessOppIdRouteImport
      parentRoute: typeof CareerBusinessRoute
    }
    '/career/business/new': {
      id: '/career/business/new'
      path: '/new'
      fullPath: '/career/business/new'
      preLoaderRoute: typeof CareerBusinessNewRouteImport
      parentRoute: typeof CareerBusinessRoute
    }
    '/career/jobs/$jobId': {
      id: '/career/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/career/jobs/$jobId'
      preLoaderRoute: typeof CareerJobsJobIdRouteImport
      parentRoute: typeof CareerJobsRoute
    }
    '/career/jobs/new': {
      id: '/career/jobs/new'
      path: '/new'
      fullPath: '/career/jobs/new'
      preLoaderRoute: typeof CareerJobsNewRouteImport
      parentRoute: typeof CareerJobsRoute
    }
    '/career/reels/new': {
      id: '/career/reels/new'
      path: '/reels/new'
      fullPath: '/career/reels/new'
      preLoaderRoute: typeof CareerReelsNewRouteImport
      parentRoute: typeof CareerRoute
    }
    '/education/$catKey/': {
      id: '/education/$catKey/'
      path: '/'
      fullPath: '/education/$catKey/'
      preLoaderRoute: typeof EducationCatKeyIndexRouteImport
      parentRoute: typeof EducationCatKeyRoute
    }
    '/education/$catKey/$subKey': {
      id: '/education/$catKey/$subKey'
      path: '/$subKey'
      fullPath: '/education/$catKey/$subKey'
      preLoaderRoute: typeof EducationCatKeySubKeyRouteImport
      parentRoute: typeof EducationCatKeyRoute
    }
    '/education/jee/$toolKey': {
      id: '/education/jee/$toolKey'
      path: '/jee/$toolKey'
      fullPath: '/education/jee/$toolKey'
      preLoaderRoute: typeof EducationJeeToolKeyRouteImport
      parentRoute: typeof EducationRoute
    }
    '/education/jee/levels': {
      id: '/education/jee/levels'
      path: '/jee/levels'
      fullPath: '/education/jee/levels'
      preLoaderRoute: typeof EducationJeeLevelsRouteImport
      parentRoute: typeof EducationRoute
    }
    '/education/neet/$toolKey': {
      id: '/education/neet/$toolKey'
      path: '/neet/$toolKey'
      fullPath: '/education/neet/$toolKey'
      preLoaderRoute: typeof EducationNeetToolKeyRouteImport
      parentRoute: typeof EducationRoute
    }
    '/education/study/': {
      id: '/education/study/'
      path: '/study'
      fullPath: '/education/study/'
      preLoaderRoute: typeof EducationStudyIndexRouteImport
      parentRoute: typeof EducationRoute
    }
    '/education/study/$exam': {
      id: '/education/study/$exam'
      path: '/study/$exam'
      fullPath: '/education/study/$exam'
      preLoaderRoute: typeof EducationStudyExamRouteImport
      parentRoute: typeof EducationRoute
    }
    '/orbit/c/$slug': {
      id: '/orbit/c/$slug'
      path: '/c/$slug'
      fullPath: '/orbit/c/$slug'
      preLoaderRoute: typeof OrbitCSlugRouteImport
      parentRoute: typeof OrbitRoute
    }
    '/orbit/projects/': {
      id: '/orbit/projects/'
      path: '/projects'
      fullPath: '/orbit/projects/'
      preLoaderRoute: typeof OrbitProjectsIndexRouteImport
      parentRoute: typeof OrbitRoute
    }
    '/orbit/projects/$projectId': {
      id: '/orbit/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/orbit/projects/$projectId'
      preLoaderRoute: typeof OrbitProjectsProjectIdRouteImport
      parentRoute: typeof OrbitRoute
    }
    '/orbit/projects/new': {
      id: '/orbit/projects/new'
      path: '/projects/new'
      fullPath: '/orbit/projects/new'
      preLoaderRoute: typeof OrbitProjectsNewRouteImport
      parentRoute: typeof OrbitRoute
    }
    '/api/public/og/post/$postId': {
      id: '/api/public/og/post/$postId'
      path: '/api/public/og/post/$postId'
      fullPath: '/api/public/og/post/$postId'
      preLoaderRoute: typeof ApiPublicOgPostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentRouteChildren {
  AgentActivityRoute: typeof AgentActivityRoute
  AgentMemoryRoute: typeof AgentMemoryRoute
  AgentPermissionsRoute: typeof AgentPermissionsRoute
  AgentUltraRoute: typeof AgentUltraRoute
  AgentIndexRoute: typeof AgentIndexRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentActivityRoute: AgentActivityRoute,
  AgentMemoryRoute: AgentMemoryRoute,
  AgentPermissionsRoute: AgentPermissionsRoute,
  AgentUltraRoute: AgentUltraRoute,
  AgentIndexRoute: AgentIndexRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface AssistantsRouteChildren {
  AssistantsToolRoute: typeof AssistantsToolRoute
  AssistantsContentCreatorRoute: typeof AssistantsContentCreatorRoute
  AssistantsDigitalTwinRoute: typeof AssistantsDigitalTwinRoute
  AssistantsEmailRoute: typeof AssistantsEmailRoute
  AssistantsScheduleRoute: typeof AssistantsScheduleRoute
  AssistantsSmartReplyRoute: typeof AssistantsSmartReplyRoute
  AssistantsIndexRoute: typeof AssistantsIndexRoute
}

const AssistantsRouteChildren: AssistantsRouteChildren = {
  AssistantsToolRoute: AssistantsToolRoute,
  AssistantsContentCreatorRoute: AssistantsContentCreatorRoute,
  AssistantsDigitalTwinRoute: AssistantsDigitalTwinRoute,
  AssistantsEmailRoute: AssistantsEmailRoute,
  AssistantsScheduleRoute: AssistantsScheduleRoute,
  AssistantsSmartReplyRoute: AssistantsSmartReplyRoute,
  AssistantsIndexRoute: AssistantsIndexRoute,
}

const AssistantsRouteWithChildren = AssistantsRoute._addFileChildren(
  AssistantsRouteChildren,
)

interface CareerBusinessRouteChildren {
  CareerBusinessOppIdRoute: typeof CareerBusinessOppIdRoute
  CareerBusinessNewRoute: typeof CareerBusinessNewRoute
}

const CareerBusinessRouteChildren: CareerBusinessRouteChildren = {
  CareerBusinessOppIdRoute: CareerBusinessOppIdRoute,
  CareerBusinessNewRoute: CareerBusinessNewRoute,
}

const CareerBusinessRouteWithChildren = CareerBusinessRoute._addFileChildren(
  CareerBusinessRouteChildren,
)

interface CareerJobsRouteChildren {
  CareerJobsJobIdRoute: typeof CareerJobsJobIdRoute
  CareerJobsNewRoute: typeof CareerJobsNewRoute
}

const CareerJobsRouteChildren: CareerJobsRouteChildren = {
  CareerJobsJobIdRoute: CareerJobsJobIdRoute,
  CareerJobsNewRoute: CareerJobsNewRoute,
}

const CareerJobsRouteWithChildren = CareerJobsRoute._addFileChildren(
  CareerJobsRouteChildren,
)

interface CareerRouteChildren {
  CareerAiRoute: typeof CareerAiRoute
  CareerAiCareerRoute: typeof CareerAiCareerRoute
  CareerApplicationsRoute: typeof CareerApplicationsRoute
  CareerBusinessRoute: typeof CareerBusinessRouteWithChildren
  CareerCompaniesRoute: typeof CareerCompaniesRoute
  CareerEventsRoute: typeof CareerEventsRoute
  CareerFeedRoute: typeof CareerFeedRoute
  CareerHubRoute: typeof CareerHubRoute
  CareerJobsRoute: typeof CareerJobsRouteWithChildren
  CareerPortfolioRoute: typeof CareerPortfolioRoute
  CareerProfileRoute: typeof CareerProfileRoute
  CareerRecruiterRoute: typeof CareerRecruiterRoute
  CareerIndexRoute: typeof CareerIndexRoute
  CareerReelsNewRoute: typeof CareerReelsNewRoute
}

const CareerRouteChildren: CareerRouteChildren = {
  CareerAiRoute: CareerAiRoute,
  CareerAiCareerRoute: CareerAiCareerRoute,
  CareerApplicationsRoute: CareerApplicationsRoute,
  CareerBusinessRoute: CareerBusinessRouteWithChildren,
  CareerCompaniesRoute: CareerCompaniesRoute,
  CareerEventsRoute: CareerEventsRoute,
  CareerFeedRoute: CareerFeedRoute,
  CareerHubRoute: CareerHubRoute,
  CareerJobsRoute: CareerJobsRouteWithChildren,
  CareerPortfolioRoute: CareerPortfolioRoute,
  CareerProfileRoute: CareerProfileRoute,
  CareerRecruiterRoute: CareerRecruiterRoute,
  CareerIndexRoute: CareerIndexRoute,
  CareerReelsNewRoute: CareerReelsNewRoute,
}

const CareerRouteWithChildren =
  CareerRoute._addFileChildren(CareerRouteChildren)

interface EduReelsRouteChildren {
  EduReelsNewRoute: typeof EduReelsNewRoute
}

const EduReelsRouteChildren: EduReelsRouteChildren = {
  EduReelsNewRoute: EduReelsNewRoute,
}

const EduReelsRouteWithChildren = EduReelsRoute._addFileChildren(
  EduReelsRouteChildren,
)

interface EducationCatKeyRouteChildren {
  EducationCatKeySubKeyRoute: typeof EducationCatKeySubKeyRoute
  EducationCatKeyIndexRoute: typeof EducationCatKeyIndexRoute
}

const EducationCatKeyRouteChildren: EducationCatKeyRouteChildren = {
  EducationCatKeySubKeyRoute: EducationCatKeySubKeyRoute,
  EducationCatKeyIndexRoute: EducationCatKeyIndexRoute,
}

const EducationCatKeyRouteWithChildren = EducationCatKeyRoute._addFileChildren(
  EducationCatKeyRouteChildren,
)

interface EducationRouteChildren {
  EducationCatKeyRoute: typeof EducationCatKeyRouteWithChildren
  EducationJeeCoachRoute: typeof EducationJeeCoachRoute
  EducationIndexRoute: typeof EducationIndexRoute
  EducationJeeToolKeyRoute: typeof EducationJeeToolKeyRoute
  EducationJeeLevelsRoute: typeof EducationJeeLevelsRoute
  EducationNeetToolKeyRoute: typeof EducationNeetToolKeyRoute
  EducationStudyExamRoute: typeof EducationStudyExamRoute
  EducationStudyIndexRoute: typeof EducationStudyIndexRoute
}

const EducationRouteChildren: EducationRouteChildren = {
  EducationCatKeyRoute: EducationCatKeyRouteWithChildren,
  EducationJeeCoachRoute: EducationJeeCoachRoute,
  EducationIndexRoute: EducationIndexRoute,
  EducationJeeToolKeyRoute: EducationJeeToolKeyRoute,
  EducationJeeLevelsRoute: EducationJeeLevelsRoute,
  EducationNeetToolKeyRoute: EducationNeetToolKeyRoute,
  EducationStudyExamRoute: EducationStudyExamRoute,
  EducationStudyIndexRoute: EducationStudyIndexRoute,
}

const EducationRouteWithChildren = EducationRoute._addFileChildren(
  EducationRouteChildren,
)

interface KnowledgeFeedRouteChildren {
  KnowledgeFeedPostIdRoute: typeof KnowledgeFeedPostIdRoute
  KnowledgeFeedNewRoute: typeof KnowledgeFeedNewRoute
}

const KnowledgeFeedRouteChildren: KnowledgeFeedRouteChildren = {
  KnowledgeFeedPostIdRoute: KnowledgeFeedPostIdRoute,
  KnowledgeFeedNewRoute: KnowledgeFeedNewRoute,
}

const KnowledgeFeedRouteWithChildren = KnowledgeFeedRoute._addFileChildren(
  KnowledgeFeedRouteChildren,
)

interface MessagesRouteChildren {
  MessagesChatIdRoute: typeof MessagesChatIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesChatIdRoute: MessagesChatIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface OrbitRouteChildren {
  OrbitPostIdRoute: typeof OrbitPostIdRoute
  OrbitExploreRoute: typeof OrbitExploreRoute
  OrbitMessagesRoute: typeof OrbitMessagesRoute
  OrbitNotificationsRoute: typeof OrbitNotificationsRoute
  OrbitPodcastsRoute: typeof OrbitPodcastsRoute
  OrbitProfileRoute: typeof OrbitProfileRoute
  OrbitReelsRoute: typeof OrbitReelsRoute
  OrbitSetupRoute: typeof OrbitSetupRoute
  OrbitIndexRoute: typeof OrbitIndexRoute
  OrbitCSlugRoute: typeof OrbitCSlugRoute
  OrbitProjectsProjectIdRoute: typeof OrbitProjectsProjectIdRoute
  OrbitProjectsNewRoute: typeof OrbitProjectsNewRoute
  OrbitProjectsIndexRoute: typeof OrbitProjectsIndexRoute
}

const OrbitRouteChildren: OrbitRouteChildren = {
  OrbitPostIdRoute: OrbitPostIdRoute,
  OrbitExploreRoute: OrbitExploreRoute,
  OrbitMessagesRoute: OrbitMessagesRoute,
  OrbitNotificationsRoute: OrbitNotificationsRoute,
  OrbitPodcastsRoute: OrbitPodcastsRoute,
  OrbitProfileRoute: OrbitProfileRoute,
  OrbitReelsRoute: OrbitReelsRoute,
  OrbitSetupRoute: OrbitSetupRoute,
  OrbitIndexRoute: OrbitIndexRoute,
  OrbitCSlugRoute: OrbitCSlugRoute,
  OrbitProjectsProjectIdRoute: OrbitProjectsProjectIdRoute,
  OrbitProjectsNewRoute: OrbitProjectsNewRoute,
  OrbitProjectsIndexRoute: OrbitProjectsIndexRoute,
}

const OrbitRouteWithChildren = OrbitRoute._addFileChildren(OrbitRouteChildren)

interface PremiumRouteChildren {
  PremiumCareerRoute: typeof PremiumCareerRoute
  PremiumCreatorRoute: typeof PremiumCreatorRoute
}

const PremiumRouteChildren: PremiumRouteChildren = {
  PremiumCareerRoute: PremiumCareerRoute,
  PremiumCreatorRoute: PremiumCreatorRoute,
}

const PremiumRouteWithChildren =
  PremiumRoute._addFileChildren(PremiumRouteChildren)

interface SettingsRouteChildren {
  SettingsDeleteAccountRoute: typeof SettingsDeleteAccountRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsDeleteAccountRoute: SettingsDeleteAccountRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ApiSamRouteChildren {
  ApiSamImageRoute: typeof ApiSamImageRoute
}

const ApiSamRouteChildren: ApiSamRouteChildren = {
  ApiSamImageRoute: ApiSamImageRoute,
}

const ApiSamRouteWithChildren =
  ApiSamRoute._addFileChildren(ApiSamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRouteWithChildren,
  AssistantsRoute: AssistantsRouteWithChildren,
  AuthRoute: AuthRoute,
  CareerRoute: CareerRouteWithChildren,
  ChildSafetyRoute: ChildSafetyRoute,
  ConnectionsRoute: ConnectionsRoute,
  CreateRoute: CreateRoute,
  EduReelsRoute: EduReelsRouteWithChildren,
  EducationRoute: EducationRouteWithChildren,
  ExploreRoute: ExploreRoute,
  FinanceRoute: FinanceRoute,
  FutureRoute: FutureRoute,
  HealthRoute: HealthRoute,
  KnowledgeRoute: KnowledgeRoute,
  KnowledgeFeedRoute: KnowledgeFeedRouteWithChildren,
  LearnRoute: LearnRoute,
  MemoryRoute: MemoryRoute,
  MessagesRoute: MessagesRouteWithChildren,
  ModerationRoute: ModerationRoute,
  NewsRoute: NewsRoute,
  NotificationsRoute: NotificationsRoute,
  OrbitRoute: OrbitRouteWithChildren,
  PremiumRoute: PremiumRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ReelsRoute: ReelsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SamRoute: SamRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ShoppingRoute: ShoppingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TranslateRoute: TranslateRoute,
  TravelRoute: TravelRoute,
  WelcomeRoute: WelcomeRoute,
  AdminEduReviewRoute: AdminEduReviewRoute,
  ApiSamRoute: ApiSamRouteWithChildren,
  ApiSmartReplyRoute: ApiSmartReplyRoute,
  ApiWelcomeVoiceRoute: ApiWelcomeVoiceRoute,
  CommunitiesSlugRoute: CommunitiesSlugRoute,
  CommunitiesNewRoute: CommunitiesNewRoute,
  PPostIdRoute: PPostIdRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  TwinUserIdRoute: TwinUserIdRoute,
  CommunitiesIndexRoute: CommunitiesIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ApiAgentPlanRoute: ApiAgentPlanRoute,
  ApiCareerJobSuggestRoute: ApiCareerJobSuggestRoute,
  ApiCareerResumeMatchRoute: ApiCareerResumeMatchRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  ApiPublicOgPostPostIdRoute: ApiPublicOgPostPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
